#
# Fichier configuration de jeux par Edmine Network.
# Dev: N12cf
# Version: 0.1
#

# MySQL.
mysql:
  host: 'ip'
  database: 'database'
  user: 'user'
  password: 'pass'

# Type de match (ranked, unranked).
type: 'ranked'

# Nombre de joueurs demandés pour lancer.
needtostart: 2

# Gestion des coffres
chests:
  number: 100
  radius: 220

# Définir les timers du jeu.
timers:
  start: 60
  startfull: 10
  preparation: 15
  nopvp: 20
  game: 1200

# Spawn du lobby principal.
spawn:
  world: 'hub'
  x: 2.5
  y: 31.0
  z: 0.5
  f: -90.5
  t: -4.0

# Gestion des cartes. (Nombre de spawns = nombre de joueurs)
maps:
  Station:
    spec:
      x: 0.5
      y: 67.0
      z: -1.5
      f: 0.0
      t: 90.0
    center:
      x: 0.5
      y: 67.0
      z: -1.5
    region:
      pos1:
        x: -244.5
        y: 147.0
        z: 115.5
      pos2:
        x: -30.5
        y: 34.0
        z: -182.5
    spawns:
      spawn1:
        x: 3.5
        y: 62.0
        z: 19.5
        f: 70.0
        t: 0.0
      spawn2:
        x: 8.5
        y: 62.0
        z: 18.5
        f: 157.0
        t: 0.0
      spawn3:
        x: 12.5
        y: 62.0
        z: 15.5
        f: 143.0
        t: 0.0
      spawn4:
        x: 16.5
        y: 62.0
        z: 11.5
        f: 126.0
        t: 0.0